### ISSUE TITLE
💩 Able to open non-scenario file in editor

### ISSUE THREAD

**Issue by DoyleSean** [andrewfisher97/EECS2311Project#1]
OS: Mac OS X 10.7 

Java Version: 7

Description: When opening a scenario file, you are able to load any text file into the editor. The editor
should only accept "scenario" files, aka files that are properly formatted as scenarios. Otherwise, the
editor will be able to produce improperly formatted scenarios.

Steps to reproduce: 
- Launch the program
- Select "Open a Scenario"
- Choose any text file

Actual Results:
- Error msg saying the file is not a compatible scenario file

Expected Results:
- File opens in editor and can be saved as a scenario

**Comment by abarnaks** [comment]
Bug solution:  only open files whose names start with keyword "scenario"
User should be informed of the naming convention beforehand
